### ISSUE TITLE
Hide Processes Running as Other Users

### ISSUE THREAD

**Issue by ghost** [Arcanyx-org/NiXium#88]
# Title

Implement `hide_uids` Functionality in NixOS.

## Description

Implement a feature in NixOS to hide processes running as other users, similar to the `hide_uids` option in FreeBSD. This would enhance system security by limiting the visibility of processes to the users who own them.

https://github.com/NiXium-org/NiXium/issues/67

**Comment by Kreyren** [comment]
Could that be implemented in a way where `@wheel` users can see the other processes? It's kinda limiting for administrators to not see other processes

**Comment by Kreyren** [comment]
#89 #90 should be united into this issue @TanvirOnGH

**Comment by ghost** [comment]
@Kreyren https://github.com/NiXium-org/NiXium/issues/98
